name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Navigate to solution directory
        run: cd ST10340607_CyberSecurity_ChatBot
        shell: bash

      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Verify Code Formatting
        run: |
          dotnet tool install -g dotnet-format
          dotnet format --verify-no-changes --check
      
      - name: Run Tests
        run: dotnet test --configuration Release --no-build

